name: Makefile CI

on:
  push:
    branches: [ "master" ]
    tags:
      - cv_pdf
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Comple LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: calkan_cv.tex

    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: calkan_cv.pdf

    - name: Release
      uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      with:
        files: calkan_cv.pdf

