name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Comple LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: calkan_cv.tex

    - name: Push new pdf
      uses: mikeal/publish-to-github-action@master

      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        PULL_REQUEST_BODY: Updates cv
        PULL_REQUEST_BRANCH: main
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    - name: Push to web page
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'calkan_cv.pdf'
        destination_repo: 'BilkentCompGen/BilkentCompGen.github.io'
        destination_folder: 'pdfs/team'
        user_email: 'calkan@gmail.com'
        user_name: 'calkan'
        commit_message: 'calkan_cv pdf update'
