name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Comple LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: calkan_cv.tex

    - name: Push new pdf
      uses: mikeal/publish-to-github-action@master

      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        PULL_REQUEST_BODY: Updates cv
        PULL_REQUEST_BRANCH: main
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
