name: Makefile CI

on:
  push:
    branches: [ "master" ]
    tags:
      - cv_pdf
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Comple LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: calkan_cv.tex

    - name: Check pdf file
      run: |
        file calkan_cv.pdf | grep -q ' PDF '

    - name: Upload calkan_cv.pdf
      run: |
        # configure git
        git config --global user.name "Can Alkan"
        git config --global user.email "calkan@gmail.com"

        git clone --depth=1 git@github.com:BilkentCompGen/BilkentCompGen.github.io.git "$GITHUB_WORKSPACE/website"
        cp -f calkan_cv.pdf "$GITHUB_WORKSPACE/website/pdfs/team/calkan_cv.pdf"
        cd "$GITHUB_WORKSPACE/website"
        git add pdfs/team/calkan_cv.pdf
        git commit -m "[github actions] update calkan_cv"
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/BilkentCompGen/BilkentCompGen.github.io.git"
      env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          PULL_REQUEST_BODY: Updates cv
          PULL_REQUEST_BRANCH: main
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
